import { Product } from './types';

export const PERFUMES: Product[] = [
  {
    id: '060',
    number: '060',
    name: 'Nº 060 – Dulce Encanto',
    brand: 'Fantasy',
    category: 'MUJER',
    family: 'Floral Frutal Gourmand',
    size: '100 ml',
    price: 19.9,
    line: 'equivalencia',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800',
    description: 'Dulce, adictivo y con vibra mágica.'
  },
  {
    id: '078',
    number: '078',
    name: 'Nº 078 – Misterio Nocturno',
    brand: 'Halloween',
    category: 'MUJER',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 19.9,
    line: 'equivalencia',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800',
    description: 'Enigmático, elegante y de los que dejan huella.'
  },
  {
    id: '167',
    number: '167',
    name: 'Nº 167 – Energía Oscura',
    brand: 'Black Opium',
    category: 'MUJER',
    family: 'Oriental Vainilla',
    size: '100 ml',
    price: 19.9,
    line: 'equivalencia',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800',
    description: 'Intenso, envolvente y con mucho carácter.'
  },
  {
    id: '174',
    number: '174',
    name: 'Nº 174 – Poder Divino',
    brand: 'Olympea',
    category: 'MUJER',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 19.9,
    line: 'equivalencia',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800',
    description: 'Fuerza, elegancia y magnetismo en cada salida.'
  },
  {
    id: '224',
    number: '224',
    name: 'Nº 224 – Fuego Azul',
    brand: 'Eros',
    category: 'HOMBRE',
    family: 'Aromática Fougère',
    size: '100 ml',
    price: 19.9,
    line: 'equivalencia',
    image: 'https://raw.githubusercontent.com/Lokeyokeria/HueleQueFlipas/main/equivalencia-hqf.jpg',
    description: 'Pasión, intensidad y energía pura.'
  },
  {
    id: '004',
    number: '004',
    name: 'Nº 004 – Ciudad Nocturna',
    brand: '212 Men',
    category: 'HOMBRE',
    family: 'Almizcle Amaderado Floral',
    size: '100 ml',
    price: 19.9,
    line: 'equivalencia',
    image: 'https://raw.githubusercontent.com/Lokeyokeria/HueleQueFlipas/main/equivalencia-hqf.jpg',
    description: 'Sofisticado, urbano y seguro.'
  },
  {
    id: '010',
    number: '010',
    name: 'Nº 010 – Oro Salvaje',
    brand: 'One Million',
    category: 'HOMBRE',
    family: 'Amaderada Especiada',
    size: '100 ml',
    price: 19.9,
    line: 'equivalencia',
    image: 'https://raw.githubusercontent.com/Lokeyokeria/HueleQueFlipas/main/equivalencia-hqf.jpg',
    description: 'Ambicioso, llamativo y con mucha presencia.'
  },
  {
    id: '015',
    number: '015',
    name: 'Nº 015 – Espíritu Valiente',
    brand: 'Only The Brave',
    category: 'HOMBRE',
    family: 'Oriental Amaderada',
    size: '100 ml',
    price: 19.9,
    line: 'equivalencia',
    image: 'https://raw.githubusercontent.com/Lokeyokeria/HueleQueFlipas/main/equivalencia-hqf.jpg',
    description: 'Actitud fuerte y personalidad marcada.'
  },
  {
    id: 'N66',
    number: 'N66',
    name: 'Nº N66 – Madera Icónica',
    brand: 'Santal 33',
    category: 'UNISEX',
    family: 'Amaderada Especiada',
    size: '100 ml',
    price: 25.0,
    line: 'nicho',
    image: 'https://raw.githubusercontent.com/Lokeyokeria/HueleQueFlipas/main/equivalencia-hqf.jpg',
    description: 'Un aroma elegante, seco y adictivo con vibra nicho de verdad.'
  },
  {
    id: 'N92',
    number: 'N92',
    name: 'Nº N92 – Fruta Infinita',
    brand: 'Erba Pura',
    category: 'UNISEX',
    family: 'Ámbar',
    size: '100 ml',
    price: 25.0,
    line: 'nicho',
    image: 'https://raw.githubusercontent.com/Lokeyokeria/HueleQueFlipas/main/equivalencia-hqf.jpg',
    description: 'Luminoso, envolvente y con ese punto jugoso que engancha.'
  },
  {
    id: 'N700',
    number: 'N700',
    name: 'Nº N700 – Sombra Nómada',
    brand: 'Ombre Nomade',
    category: 'HOMBRE',
    family: 'Ámbar Amaderada',
    size: '100 ml',
    price: 25.0,
    line: 'nicho',
    image: 'https://raw.githubusercontent.com/Lokeyokeria/HueleQueFlipas/main/equivalencia-hqf.jpg',
    description: 'Oscuro, elegante y profundo. De los que se recuerdan.'
  },
  {
    id: 'N800',
    number: 'N800',
    name: 'Nº N800 – Oro Oriental',
    brand: 'Arabians Tonka',
    category: 'UNISEX',
    family: 'Ámbar Amaderada',
    size: '100 ml',
    price: 25.0,
    line: 'nicho',
    image: 'https://raw.githubusercontent.com/Lokeyokeria/HueleQueFlipas/main/equivalencia-hqf.jpg',
    description: 'Intenso, cálido y poderoso. Un aroma de presencia total.'
  }
];
