import { Product } from './types';

const HQF_IMAGE =
  'https://raw.githubusercontent.com/Lokeyokeria/HueleQueFlipas/main/equivalencia-hqf.jpg';

export const PERFUMES: Product[] = [
  // MUJER
  {
    id: '060',
    number: '060',
    name: 'Nº 060 – Dulce Encanto',
    brand: 'Fantasy',
    category: 'MUJER',
    family: 'Floral Frutal Gourmand',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Dulce, adictiva y con un fondo gourmand muy femenino.'
  },
  {
    id: '078',
    number: '078',
    name: 'Nº 078 – Misterio Nocturno',
    brand: 'Halloween',
    category: 'MUJER',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Un perfume floral oriental con un aire misterioso y envolvente.'
  },
  {
    id: '167',
    number: '167',
    name: 'Nº 167 – Energía Oscura',
    brand: 'Black Opium',
    category: 'MUJER',
    family: 'Oriental Vainilla',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Intensa, moderna y con un toque adictivo de vainilla oriental.'
  },
  {
    id: '174',
    number: '174',
    name: 'Nº 174 – Poder Divino',
    brand: 'Olympea',
    category: 'MUJER',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Femenina, luminosa y con un punto elegante y poderoso.'
  },
  {
    id: 'M107',
    number: 'M107',
    name: 'Nº M107 – Paradoxe Intense',
    brand: 'Prada Paradoxe Intense',
    category: 'MUJER',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Una floral oriental intensa con pera, neroli, jazmín y un fondo avainillado y ambarado.'
  },
  {
    id: 'M104',
    number: 'M104',
    name: 'Nº M104 – La Bomba',
    brand: 'La Bomba Carolina Herrera',
    category: 'MUJER',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Exótica y femenina, con pitahaya, peonía roja y un fondo dulce de vainilla y pachulí.'
  },
  {
    id: 'M102',
    number: 'M102',
    name: 'Nº M102 – Zadig Eau de Parfum',
    brand: 'Zadig Eau de Parfum',
    category: 'MUJER',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Especiada y cremosa, con neroli, flor de azahar, vainilla y sándalo.'
  },
  {
    id: 'M101',
    number: 'M101',
    name: "Nº M101 – La Vie Est Belle L'Elixir",
    brand: "La Vie Est Belle L'Elixir",
    category: 'MUJER',
    family: 'Floral Frutal Gourmand',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Golosa y sofisticada, con frambuesa, licor, rosa y un fondo de cacao y cuero.'
  },
  {
    id: 'M96',
    number: 'M96',
    name: "Nº M96 – J'Adore L'Or Essence",
    brand: "J'Adore L'Or Essence",
    category: 'MUJER',
    family: 'Floral',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Un floral elegante y luminoso con rosa, jazmín, ylang-ylang y vainilla.'
  },
  {
    id: 'M95',
    number: 'M95',
    name: 'Nº M95 – Million Gold',
    brand: 'Million Gold Rabanne',
    category: 'MUJER',
    family: 'Almizcle Floral Amaderado',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Moderna y envolvente, con pera, rosa, jazmín y un fondo suave de almizcle y vainilla.'
  },
  {
    id: 'M94',
    number: 'M94',
    name: 'Nº M94 – Yara',
    brand: 'Yara Lattafa Perfumes',
    category: 'MUJER',
    family: 'Ámbar Vainilla',
    size: '100 ml',
    price: 19.90,
    line: 'arabe',
    image: HQF_IMAGE,
    description: 'Dulce, tropical y cremosa, con vainilla, frutas tropicales y sándalo.'
  },
  {
    id: 'M90',
    number: 'M90',
    name: 'Nº M90 – Ángel Elixir',
    brand: 'Ángel Elixir Mugler',
    category: 'MUJER',
    family: 'Floral Frutal Gourmand',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Intensa y seductora, con jazmín, flor de azahar, vainilla Bourbon y un toque moderno.'
  },
  {
    id: 'M89',
    number: 'M89',
    name: 'Nº M89 – Devotion',
    brand: 'Devotion Dolce & Gabbana',
    category: 'MUJER',
    family: 'Ámbar Vainilla',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Golosa y deliciosa, con limón confitado, panacota, ron y vainilla.'
  },
  {
    id: 'M88',
    number: 'M88',
    name: 'Nº M88 – Goddess',
    brand: 'Goddess Burberry',
    category: 'MUJER',
    family: 'Aromática',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Suave, avainillada y elegante, con lavanda, cacao y una vainilla muy envolvente.'
  },
  {
    id: 'M87',
    number: 'M87',
    name: 'Nº M87 – Gaultier Divine',
    brand: 'Gaultier Divine Jean Paul Gaultier',
    category: 'MUJER',
    family: 'Ámbar Floral',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Femenina y luminosa, con jazmín, azucena, bergamota y un fondo dulce de merengue.'
  },
  {
    id: 'M85',
    number: 'M85',
    name: 'Nº M85 – Dylan Purple',
    brand: 'Versace Pour Femme Dylan Purple',
    category: 'MUJER',
    family: 'Floral Frutal',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Fresca, afrutada y moderna, con pera, bergamota, fresia y un fondo limpio.'
  },
  {
    id: 'M82',
    number: 'M82',
    name: 'Nº M82 – Toy 2 Bubble Gum',
    brand: 'Toy 2 Bubble Gum Moschino',
    category: 'MUJER',
    family: 'Floral Frutal',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Divertida y golosa, con chicle, frutas confitadas, rosa y un fondo suave de almizcle.'
  },
  {
    id: 'M79',
    number: 'M79',
    name: 'Nº M79 – Q',
    brand: 'Q by Dolce & Gabbana',
    category: 'MUJER',
    family: 'Aromática Frutal',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Frutal y elegante, con limón siciliano, cereza, heliotropo y cedro.'
  },
  {
    id: 'M75',
    number: 'M75',
    name: 'Nº M75 – Paradoxe',
    brand: 'Paradoxe Prada',
    category: 'MUJER',
    family: 'Ámbar Floral',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Femenina, sofisticada y avainillada, con pera, neroli, jazmín y ámbar.'
  },
  {
    id: 'M72',
    number: 'M72',
    name: 'Nº M72 – Fame',
    brand: 'Fame Paco Rabanne',
    category: 'MUJER',
    family: 'Floral Amaderada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Moderna y chispeante, con mango, jazmín, caramelo y un fondo cálido de vainilla.'
  },

  // HOMBRE
  {
    id: '224',
    number: '224',
    name: 'Nº 224 – Fuego Azul',
    brand: 'Eros',
    category: 'HOMBRE',
    family: 'Aromática Fougère',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Pasión, intensidad y energía pura.'
  },
  {
    id: '004',
    number: '004',
    name: 'Nº 004 – Ciudad Nocturna',
    brand: '212 Men',
    category: 'HOMBRE',
    family: 'Almizcle Amaderado Floral',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Sofisticado, urbano y seguro.'
  },
  {
    id: '010',
    number: '010',
    name: 'Nº 010 – Oro Salvaje',
    brand: 'One Million',
    category: 'HOMBRE',
    family: 'Amaderada Especiada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Ambicioso, llamativo y con mucha presencia.'
  },
  {
    id: '015',
    number: '015',
    name: 'Nº 015 – Espíritu Valiente',
    brand: 'Only The Brave',
    category: 'HOMBRE',
    family: 'Oriental Amaderada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Actitud fuerte y personalidad marcada.'
  },
  {
    id: 'D32',
    number: 'D32',
    name: 'Nº D32 – Eros Flame',
    brand: 'Eros Flame de Versace',
    category: 'HOMBRE',
    family: 'Amaderada Especiada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Una fragancia intensa y cálida, con cítricos, pimienta y un fondo amaderado y avainillado.'
  },
  {
    id: 'D30',
    number: 'D30',
    name: 'Nº D30 – Boss Bottled Beyond',
    brand: 'Boss Bottled Beyond Hugo Boss',
    category: 'HOMBRE',
    family: 'Cuero',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Directa y masculina, con jengibre, cuero y un fondo amaderado sobrio.'
  },
  {
    id: 'D20',
    number: 'D20',
    name: 'Nº D20 – Le Male Elixir',
    brand: 'Le Male Elixir de Jean Paul Gaultier',
    category: 'HOMBRE',
    family: 'Oriental Fougère',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Seductora y golosa, con lavanda, vainilla, benjuí, miel y tabaco.'
  },
  {
    id: 'D21',
    number: 'D21',
    name: 'Nº D21 – Million Gold',
    brand: 'Million Gold Rabanne',
    category: 'HOMBRE',
    family: 'Amaderada Aromática',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Luminosa y moderna, con mandarina, cedro y un fondo amaderado elegante.'
  },
  {
    id: 'D22',
    number: 'D22',
    name: 'Nº D22 – Acqua di Giò Profumo',
    brand: 'Acqua di Giò Profumo Giorgio Armani',
    category: 'HOMBRE',
    family: 'Aromática Acuática',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Fresca y profunda, con notas marinas, bergamota, romero e incienso.'
  },
  {
    id: 'D23',
    number: 'D23',
    name: 'Nº D23 – Devotion Pour Homme',
    brand: 'Devotion Pour Homme Dolce & Gabbana',
    category: 'HOMBRE',
    family: 'Amaderada Especiada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Cítrica y con carácter, con limón, café y un fondo de pachulí.'
  },
  {
    id: '429',
    number: '429',
    name: 'Nº 429 – Invictus Victory',
    brand: 'Invictus Victory',
    category: 'HOMBRE',
    family: 'Oriental',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Potente y adictiva, con pimienta rosa, lavanda, vainilla y haba tonka.'
  },
  {
    id: 'D24',
    number: 'D24',
    name: 'Nº D24 – Bottled Absolu',
    brand: 'Bottled Absolu Hugo Boss',
    category: 'HOMBRE',
    family: 'Amaderada Aromática',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Intensa y sofisticada, con incienso, cuero, pachuli, mirra y un fondo cálido.'
  },
  {
    id: 'D25',
    number: 'D25',
    name: 'Nº D25 – Stronger With You Intensely',
    brand: 'Emporio Armani Stronger With You Intensely',
    category: 'HOMBRE',
    family: 'Oriental Fougère',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Envolvente y adictiva, con tofe, canela, vainilla, ámbar y haba tonka.'
  },
  {
    id: 'D26',
    number: 'D26',
    name: 'Nº D26 – Uomo Born in Roma',
    brand: 'Valentino Uomo Born in Roma',
    category: 'HOMBRE',
    family: 'Amaderada Especiada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Moderna y elegante, con notas minerales, violeta, jengibre y vetiver.'
  },
  {
    id: 'D27',
    number: 'D27',
    name: 'Nº D27 – Le Beau Paradise Garden',
    brand: 'Le Beau Paradise Garden Jean Paul Gaultier',
    category: 'HOMBRE',
    family: 'Green Acuatic',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Exótica y fresca, con notas verdes, menta, coco, higo y un fondo cremoso.'
  },
  {
    id: 'D28',
    number: 'D28',
    name: 'Nº D28 – Paradigme',
    brand: 'Paradigme Prada',
    category: 'HOMBRE',
    family: 'Oriental Amaderada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Elegante y refinada, con bergamota, almizcle, geranio y un fondo resinoso.'
  },
  {
    id: 'D14',
    number: 'D14',
    name: 'Nº D14 – Toy Boy',
    brand: 'Toy Boy Moschino',
    category: 'HOMBRE',
    family: 'Amaderada Especiada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Original y especiada, con pimienta rosa, rosa, clavo y un fondo ambarado.'
  },
  {
    id: 'D15',
    number: 'D15',
    name: 'Nº D15 – MYSLF',
    brand: 'MYSLF Yves Saint Laurent',
    category: 'HOMBRE',
    family: 'Aromática',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Limpia y moderna, con bergamota, flor de azahar y un fondo de pachulí.'
  },
  {
    id: 'D16',
    number: 'D16',
    name: 'Nº D16 – Invictus Victory Elixir',
    brand: 'Invictus Victory Elixir Paco Rabanne',
    category: 'HOMBRE',
    family: 'Ámbar Amaderada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Intensa y profunda, con pimienta negra, lavanda, incienso y vainilla.'
  },
  {
    id: 'D02',
    number: 'D02',
    name: 'Nº D02 – Le Male Le Parfum',
    brand: 'Le Male Le Parfum Jean Paul Gaultier',
    category: 'HOMBRE',
    family: 'Oriental',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Elegante y seductora, con cardamomo, lavanda, iris y un fondo oriental avainillado.'
  },
  {
    id: 'D03',
    number: 'D03',
    name: 'Nº D03 – 212 Heroes',
    brand: '212 Heroes Carolina Herrera',
    category: 'HOMBRE',
    family: 'Aromática Frutal',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Joven y distinta, con pera, jengibre, salvia y un fondo de almizcle y cuero.'
  },
  {
    id: 'D04',
    number: 'D04',
    name: 'Nº D04 – Phantom',
    brand: 'Phantom Paco Rabanne',
    category: 'HOMBRE',
    family: 'Amaderada Aromática',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Moderna y vibrante, con lavanda, limón, manzana, vainilla y vetiver.'
  },
  {
    id: 'D05',
    number: 'D05',
    name: 'Nº D05 – Scandal Pour Homme',
    brand: 'Scandal Pour Homme Jean Paul Gaultier',
    category: 'HOMBRE',
    family: 'Ámbar Amaderada',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Golosa y masculina, con mandarina, caramelo, haba tonka y vetiver.'
  },
  {
    id: 'D07',
    number: 'D07',
    name: "Nº D07 – Ralph's Club",
    brand: "Ralph's Club Ralph Lauren",
    category: 'HOMBRE',
    family: 'Amaderada Aromática',
    size: '100 ml',
    price: 19.90,
    line: 'normal',
    image: HQF_IMAGE,
    description: 'Elegante y limpia, con lavanda, esclarea, cedro y vetiver.'
  },

  // FRAGANCIAS SELECTAS Y ÁRABES
  {
    id: '8001',
    number: '8001',
    name: 'Nº 8001 – Yum Pistachio Gelato 33',
    brand: 'Yum Pistachio Gelato 33 Kayali',
    category: 'UNISEX',
    family: 'Gourmand',
    size: '100 ml',
    price: 19.90,
    line: 'selecta',
    image: HQF_IMAGE,
    description: 'Dulce, cremosa y divertida, con pistacho, avellana y un fondo goloso muy especial.'
  },
  {
    id: '8002',
    number: '8002',
    name: 'Nº 8002 – Lovefest Burning Cherry 48',
    brand: 'Lovefest Burning Cherry 48 Kayali',
    category: 'UNISEX',
    family: 'Ámbar Amaderada',
    size: '100 ml',
    price: 19.90,
    line: 'selecta',
    image: HQF_IMAGE,
    description: 'Cereza intensa, cálida y sofisticada, con rosa, praliné y un fondo ahumado.'
  },
  {
    id: '8003',
    number: '8003',
    name: 'Nº 8003 – I Want Choo Forever',
    brand: 'I Want Choo Forever Jimmy Choo',
    category: 'MUJER',
    family: 'Floral Frutal Gourmand',
    size: '100 ml',
    price: 19.90,
    line: 'selecta',
    image: HQF_IMAGE,
    description: 'Femenina y seductora, con rosa, cereza, vainilla y un toque elegante.'
  },
  {
    id: '8004',
    number: '8004',
    name: 'Nº 8004 – Vanilla 28',
    brand: 'Vanilla 28 Kayali',
    category: 'UNISEX',
    family: 'Oriental Vainilla',
    size: '100 ml',
    price: 19.90,
    line: 'selecta',
    image: HQF_IMAGE,
    description: 'Avainillada, cálida y muy adictiva, perfecta para amantes de los aromas dulces.'
  },
  {
    id: '8012',
    number: '8012',
    name: 'Nº 8012 – Costa Azzurra',
    brand: 'Costa Azzurra Tom Ford',
    category: 'UNISEX',
    family: 'Aromática Acuática',
    size: '100 ml',
    price: 19.90,
    line: 'selecta',
    image: HQF_IMAGE,
    description: 'Fresca, marina y elegante, con salida aromática y un fondo amaderado refinado.'
  },
  {
    id: '8013',
    number: '8013',
    name: 'Nº 8013 – Eden Juicy Apple 01',
    brand: 'Eden Juicy Apple 01 Kayali',
    category: 'UNISEX',
    family: 'Floral Frutal',
    size: '100 ml',
    price: 19.90,
    line: 'selecta',
    image: HQF_IMAGE,
    description: 'Jugosa, alegre y afrutada, con manzana roja, frutos del bosque y un fondo suave.'
  },
  {
    id: '8014',
    number: '8014',
    name: 'Nº 8014 – Lost Cherry',
    brand: 'Lost Cherry Tom Ford',
    category: 'UNISEX',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 19.90,
    line: 'selecta',
    image: HQF_IMAGE,
    description: 'Golosa y sensual, con almendra amarga, cereza negra y un fondo cálido y licoroso.'
  },
  {
    id: '8015',
    number: '8015',
    name: 'Nº 8015 – Asad',
    brand: 'Asad Lattafa Perfumes',
    category: 'HOMBRE',
    family: 'Oriental',
    size: '100 ml',
    price: 19.90,
    line: 'arabe',
    image: HQF_IMAGE,
    description: 'Intensa, especiada y masculina, con pimienta negra, tabaco y un fondo oscuro.'
  },
  {
    id: '8016',
    number: '8016',
    name: 'Nº 8016 – Asad Bourbon',
    brand: 'Asad Bourbon Lattafa Perfumes',
    category: 'HOMBRE',
    family: 'Oriental Especiada',
    size: '100 ml',
    price: 19.90,
    line: 'arabe',
    image: HQF_IMAGE,
    description: 'Potente y cálida, con pimientas, cacao, nuez moscada y vainilla bourbon.'
  },
  {
    id: '8017',
    number: '8017',
    name: 'Nº 8017 – Odyssey Mandarin Sky Elixir',
    brand: 'Odyssey Mandarin Sky Elixir Armaf',
    category: 'UNISEX',
    family: 'Oriental Especiada',
    size: '100 ml',
    price: 19.90,
    line: 'arabe',
    image: HQF_IMAGE,
    description: 'Cítrica y especiada, con mandarina, jengibre y un fondo avainillado moderno.'
  },

  // FRAGANCIAS NICHO
  {
    id: '7015',
    number: '7015',
    name: 'Nº 7015 – Portrait of a Lady',
    brand: 'Portrait of a Lady Frederic Malle',
    category: 'MUJER',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Una fragancia intensa, elegante y profunda, con rosa especiada y un fondo cálido y sofisticado.'
  },
  {
    id: '7016',
    number: '7016',
    name: 'Nº 7016 – Guidance',
    brand: 'Guidance Amouage',
    category: 'UNISEX',
    family: 'Floral Frutal',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Suave, envolvente y muy especial, con rosa, jazmín, vainilla y un fondo elegante y cremoso.'
  },
  {
    id: '7000',
    number: '7000',
    name: 'Nº 7000 – Ombre Nomade',
    brand: 'Ombre Nomade Louis Vuitton',
    category: 'HOMBRE',
    family: 'Ámbar Amaderada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Oscura, intensa y muy lujosa, con oud, cuero, especias y un fondo profundo y elegante.'
  },
  {
    id: '7001',
    number: '7001',
    name: 'Nº 7001 – Absolu Aventus',
    brand: 'Absolu Creed Aventus',
    category: 'HOMBRE',
    family: 'Cítrica',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Vibrante y refinada, con pomelo, bergamota, jengibre y un fondo seco y elegante.'
  },
  {
    id: '7002',
    number: '7002',
    name: 'Nº 7002 – Carmina',
    brand: 'Carmina Creed',
    category: 'MUJER',
    family: 'Almizcle Floral Amaderada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Femenina, intensa y sofisticada, con cereza negra, rosa de mayo y un fondo cálido y sensual.'
  },
  {
    id: '7003',
    number: '7003',
    name: 'Nº 7003 – Aqua Media Cologne Forte',
    brand: 'Aqua Media Cologne Forte Maison Francis Kurkdjian',
    category: 'UNISEX',
    family: 'Cítrica',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Fresca, limpia y luminosa, con cítricos verdes, té matcha y un fondo suave y moderno.'
  },
  {
    id: '7004',
    number: '7004',
    name: 'Nº 7004 – Acqua di Sale',
    brand: 'Acqua di Sale Profumum Roma',
    category: 'UNISEX',
    family: 'Oriental Especiado',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Marina, especiada y original, con lavanda, mirto, notas saladas y un fondo suave y cálido.'
  },
  {
    id: '7005',
    number: '7005',
    name: 'Nº 7005 – Vanilla Sex',
    brand: 'Vanilla Sex Tom Ford',
    category: 'UNISEX',
    family: 'Oriental',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Avainillada, cremosa y envolvente, con almendra amarga, flores y un fondo muy sensual.'
  },
  {
    id: '7006',
    number: '7006',
    name: 'Nº 7006 – Torino22',
    brand: 'Torino22 Xerjoff',
    category: 'UNISEX',
    family: 'Amaderada Aromática',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Fresca y sofisticada, con eucalipto, azafrán, bergamota y un fondo seco y elegante.'
  },
  {
    id: '7007',
    number: '7007',
    name: 'Nº 7007 – Beso Dorado',
    brand: 'Beso Dorado Beso Beach Perfumes',
    category: 'UNISEX',
    family: 'Amaderada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Cálida, especiada y elegante, con lavanda, geranio, vetiver y un fondo con mucha personalidad.'
  },
  {
    id: '7008',
    number: '7008',
    name: 'Nº 7008 – XJ 1861 Naxos',
    brand: 'XJ 1861 Naxos Xerjoff',
    category: 'UNISEX',
    family: 'Cítrica Gourmand',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Dulce, elegante y adictiva, con miel, canela, lavanda y un fondo cálido de tabaco y vainilla.'
  },
  {
    id: '7009',
    number: '7009',
    name: 'Nº 7009 – Annone',
    brand: 'Annone Pantheon Roma',
    category: 'UNISEX',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Exótica y distinguida, con azafrán, mango, rosa e iris sobre un fondo amaderado y almizclado.'
  },
  {
    id: '7010',
    number: '7010',
    name: 'Nº 7010 – Terroni',
    brand: 'Terroni Orto Parisi',
    category: 'UNISEX',
    family: 'Oriental Amaderada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Intensa, terrosa y poderosa, con frambuesa, ámbar, vetiver, pachulí y vainilla.'
  },
  {
    id: 'N64',
    number: 'N64',
    name: 'Nº N64 – The Matcha 26',
    brand: 'The Matcha 26 Le Labo',
    category: 'UNISEX',
    family: 'Amaderada Musk',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Serena y elegante, con cítricos suaves, iris, sándalo, incienso y un fondo almizclado.'
  },
  {
    id: 'N65',
    number: 'N65',
    name: 'Nº N65 – Philosykos Eau de Parfum',
    brand: 'Philosykos Eau de Parfum Diptyque',
    category: 'UNISEX',
    family: 'Amaderada Aromática',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Verde, cremosa y natural, con hoja de higuera, coco y un fondo amaderado muy elegante.'
  },
  {
    id: 'N66',
    number: 'N66',
    name: 'Nº N66 – Santal 33',
    brand: 'Santal 33 Le Labo',
    category: 'UNISEX',
    family: 'Amaderada Especiada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Seca, icónica y sofisticada, con violeta, cardamomo, cuero y sándalo.'
  },
  {
    id: 'N67',
    number: 'N67',
    name: 'Nº N67 – Another 13',
    brand: 'Another 13 Le Labo',
    category: 'UNISEX',
    family: 'Floral Ambarada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Minimalista y adictiva, con pera, ámbar y musk en un aroma limpio y muy moderno.'
  },
  {
    id: 'N68',
    number: 'N68',
    name: 'Nº N68 – Thé Noir 29',
    brand: 'Thé Noir 29 Le Labo',
    category: 'UNISEX',
    family: 'Aromática',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Profunda y elegante, con higo, bergamota, vetiver, tabaco y un fondo suave y oscuro.'
  },
  {
    id: 'N69',
    number: 'N69',
    name: 'Nº N69 – Tam Dao Eau de Toilette',
    brand: 'Tam Dao Eau de Toilette Diptyque',
    category: 'UNISEX',
    family: 'Almizcle Floral Amaderado',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Suave, amaderada y refinada, con ciprés, rosa, sándalo, cedro y ámbar.'
  },
  {
    id: 'N35',
    number: 'N35',
    name: 'Nº N35 – Baccarat Rouge 540',
    brand: 'Baccarat Rouge 540 Maison Francis Kurkdjian',
    category: 'UNISEX',
    family: 'Oriental Floral',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Luminosa, adictiva y muy reconocible, con jazmín, azafrán, amberwood y cedro.'
  },
  {
    id: 'N37',
    number: 'N37',
    name: 'Nº N37 – Neroli Portofino',
    brand: 'Neroli Portofino Tom Ford',
    category: 'UNISEX',
    family: 'Cítrica Aromática',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Fresca, limpia y mediterránea, con neroli, cítricos, lavanda y azahar.'
  },
  {
    id: 'N196',
    number: 'N196',
    name: 'Nº N196 – Tobacco Vanille',
    brand: 'Tobacco Vanille Tom Ford',
    category: 'UNISEX',
    family: 'Oriental Especiada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Cálida, intensa y golosa, con tabaco, haba tonka, vainilla y cacao.'
  },
  {
    id: 'N228',
    number: 'N228',
    name: 'Nº N228 – Aventus',
    brand: 'Aventus de Creed',
    category: 'HOMBRE',
    family: 'Chipre Frutal',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Masculina, elegante y muy conocida, con bergamota, piña, abedul y musgo de roble.'
  },
  {
    id: 'N245',
    number: 'N245',
    name: 'Nº N245 – Viking',
    brand: 'Viking Creed',
    category: 'HOMBRE',
    family: 'Amaderada Aromática',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Potente y fresca, con pimienta rosa, cítricos, vetiver y un fondo elegante y seco.'
  },
  {
    id: '8000',
    number: '8000',
    name: 'Nº 8000 – Arabians Tonka',
    brand: 'Arabians Tonka de Montale',
    category: 'UNISEX',
    family: 'Ámbar Amaderada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Intensa, oscura y poderosa, con rosa, oud, ámbar y un fondo cálido y envolvente.'
  },
  {
    id: '8005',
    number: '8005',
    name: 'Nº 8005 – Indomable',
    brand: 'Indomable de Morph',
    category: 'UNISEX',
    family: 'Oriental Amaderada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Cálida, elegante y con mucho carácter, con madera de oud, azúcar y cachemira.'
  },
  {
    id: '8006',
    number: '8006',
    name: 'Nº 8006 – Red Tobacco',
    brand: 'Red Tobacco de Mancera',
    category: 'UNISEX',
    family: 'Amaderada Especiada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Brutal, intensa y especiada, con canela, oud, incienso, tabaco y vainilla.'
  },
  {
    id: '8007',
    number: '8007',
    name: 'Nº 8007 – Intense Pepper',
    brand: 'Intense Pepper de Montale',
    category: 'UNISEX',
    family: 'Oriental Especiada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Picante, seca y sofisticada, con pimienta, oud, almizcle blanco y ámbar.'
  },
  {
    id: '8008',
    number: '8008',
    name: 'Nº 8008 – Zeta',
    brand: 'Zeta de Morph',
    category: 'UNISEX',
    family: 'Especial',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Un perfume diferente y muy personal, con un perfil especial y moderno.'
  },
  {
    id: '8009',
    number: '8009',
    name: 'Nº 8009 – N 6',
    brand: 'N 6 de Morph',
    category: 'UNISEX',
    family: 'Floral Ambarada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Suave y elegante, con violeta de Parma, rosa de Damasco y un fondo almizclado.'
  },
  {
    id: '8010',
    number: '8010',
    name: 'Nº 8010 – Blu Mare',
    brand: 'Blu Mare de Giardini Di Toscana',
    category: 'UNISEX',
    family: 'Cítrica Aromática',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Limpia y marina, con bergamota, limón, ciprés y un fondo ambarado elegante.'
  },
  {
    id: '8011',
    number: '8011',
    name: 'Nº 8011 – Bois Imperial',
    brand: 'Bois Imperial Essential Parfums',
    category: 'UNISEX',
    family: 'Aromática Especiada',
    size: '100 ml',
    price: 25.00,
    line: 'nicho',
    image: HQF_IMAGE,
    description: 'Muy elegante y actual, con albahaca, pimienta, vetiver y un fondo amaderado refinado.'
  }
];
